- name: Install Apache (Specific Version)
  apt:
    name: "apache2={{ item.version }}*"
    state: present
  when: item.version is defined and item.version != ""

- name: Install Apache (Auto Latest Version)
  apt:
    name: apache2
    state: latest
  when: item.version is not defined or item.version == ""

# 서비스 상태 확인
- name: Ensure Apache service is started
  service:
    name: apache
    state: started
    enabled: yes